/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.simonscholz

import com.apollographql.apollo.ApolloClient
import dev.simonscholz.type.InboundProcessStatus

suspend fun main() {
    val token = "your_bearer_token_here"

    val apolloClient =
        ApolloClient
            .Builder()
            .serverUrl("https://{projectId}.graphql.fulfillmenttools.com/graphql")
            .addHttpHeader("Authorization", "Bearer $token")
            .build()

    val response =
        apolloClient
            .query(InboundProcessesQuery(status = InboundProcessStatus.OPEN))
            .execute()

    if (response.errors.isNullOrEmpty() && response.exception == null) {
        println("inboundProcessesV2.totalCount=${response.data?.inboundProcessesV2?.pageInfo}")
        println("inboundProcessesV2.edges=${response.data?.inboundProcessesV2?.edges}")
    } else {
        println("Errors: ${response.errors}")
        println("Exception: ${response.exception}")
    }
}
