/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.simonscholz

import com.apollographql.apollo.ApolloClient
import com.apollographql.apollo.api.Optional
import dev.simonscholz.InboundProcessesQuery.InboundProcessesV2
import dev.simonscholz.type.InboundProcessStatus
import java.io.File
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.OffsetDateTime
import java.time.ZoneId

suspend fun fetchAllInboundProcesses(
    apolloClient: ApolloClient,
    status: InboundProcessStatus,
    after: Optional<String?> = Optional.absent(),
): List<InboundProcessesV2> {
    val allPages = mutableListOf<InboundProcessesV2>()
    var nextCursor: Optional<String?> = after
    var hasNextPage = true
    while (hasNextPage) {
        val response =
            apolloClient
                .query(InboundProcessesQuery(status = status, after = nextCursor))
                .execute()
        if (!response.errors.isNullOrEmpty()) {
            println("Errors: ${response.errors}")
            break
        }
        response.data?.inboundProcessesV2?.let { allPages.add(it) }
        val pageInfo = response.data?.inboundProcessesV2?.pageInfo
        hasNextPage = pageInfo?.hasNextPage == true
        nextCursor = if (hasNextPage) Optional.presentIfNotNull(pageInfo?.endCursor) else Optional.absent()
    }
    return allPages
}

suspend fun main() {
    val token = "your_bearer_token_here"

    val berlinZone = ZoneId.of("Europe/Berlin")

    val apolloClient =
        ApolloClient
            .Builder()
            .serverUrl("https://{projectId}.graphql.fulfillmenttools.com/graphql")
            .addHttpHeader("Authorization", "Bearer $token")
            .build()

    val inboundProcessesV2 =
        fetchAllInboundProcesses(
            apolloClient,
            InboundProcessStatus.OPEN,
        )

    println("Total pages fetched: ${inboundProcessesV2.size}")

    val allEdges = inboundProcessesV2.flatMap { ib: InboundProcessesV2 -> ib.edges!! }

    println("Total edges fetched: ${allEdges.size}")

    val tenPM = LocalTime.of(23, 0)

    val tenPMEdges =
        allEdges.filter { edge ->
            edge?.node?.purchaseOrder?.let { purchase ->
                val localTime = OffsetDateTime.parse(purchase.requestedDate.value.toString()).toLocalTime()

                tenPM.equals(localTime)
            } == true
        }

    println("tenPMEdges size: ${tenPMEdges.size}")

    allEdges.forEach { edge ->
        edge?.node?.let { node ->

            val purchase = node.purchaseOrder ?: return@let

            val offsetTime =
                OffsetDateTime
                    .parse(purchase.requestedDate.value.toString())

            val localTime = offsetTime.toLocalTime()

            val type = purchase.requestedDate.value::class.simpleName

            require(type == "String") { "Expected String but got $type" }

            if (tenPM.equals(localTime)) {
                println("Requested Date: ${purchase.requestedDate.value}")
                println("Local Time: $localTime")
                val zoned = offsetTime.toZonedDateTime()
                println("Zoned Date Time: $zoned")
                val berlin = zoned.withZoneSameInstant(berlinZone)
                println("Zoned Date Time Berlin: $berlin")
                val cutOffTime =
                    when (node.facilityRef) {
                        "307c024e-5703-4977-9074-b3b69c38c355" -> LocalTime.of(13, 30)
                        "4b183614-c9ae-4d31-a285-013edf299d38" -> LocalTime.of(19, 30)
                        else -> throw IllegalArgumentException("Unexpected facilityRef: ${node.facilityRef}")
                    }
                val newDate = LocalDateTime.of(berlin.toLocalDate(), cutOffTime)
                println("New Date Time: $newDate")
                val newOffsetDate = newDate.atZone(berlinZone).toOffsetDateTime()
                println("New Offset Date Time: $newOffsetDate")

                // write node.id and newOffsetDate to a csv file
                val csvFile = File("output.csv")
                if (!csvFile.exists()) {
                    csvFile.writeText("id,newOffsetDate,oldDate\n") // Write header if file doesn't exist
                }
                csvFile.appendText("${node.id},$newOffsetDate, ${purchase.requestedDate.value}\n")
            }
        }
    }
}
