openapi: 3.0.3
info:
  title: Sample Developer API
  description: This is a sample server for developers.
  contact:
    name: Simon Scholz
    url: https://simonscholz.github.io/
    email: opensource.simon@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://localhost:8080/{basePath}
    description: Local development server
    variables:
      basePath:
        enum:
          - 'v1'
          - 'v2'
        # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
        default: v2
paths:
  /developers:
    get:
      tags:
        - developers
      summary: Get developers
      operationId: getDevelopers
      description: Returns all developers the application handles
      responses:
        '200':
          description: A list of developers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Developer'
components:
  schemas:
    Money:
      type: object
      required:
        - amount
        - currency
      properties:
        amount:
          type: number
          format: decimal
          example: 123.45
        currency:
          pattern: ^[A-Z]{3}$
          type: string
          description: Currency code according to ISO 4217 e.g. EUR for euro, CHF
            for swiss franc etc.
      example:
        amount: 113.96
        currency: EUR
    Developer:
      type: object
      properties:
        name:
          type: string
        role:
          type: string
        salary:
          $ref: '#/components/schemas/Money'
        commits:
          type: integer
          format: int32
    Problem:
      type: object
      description: Problem response as specified in RFC 7807.
      required:
        - title
        - status
      properties:
        type:
          type: string
          description: A URI reference according to RFC 3986 that identifies the problem type.
          default: about:blank
        title:
          type: string
          description: A short, human-readable summary of the problem type.
        status:
          type: integer
          format: int32
          description: The HTTP status code according to RFC 7231.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem.
