openapi: 3.0.3
info:
  title: GitHub Contributors API
  description: Just a single part of the API. See https://docs.github.com/en/rest/reference/repos#list-repository-contributors
  version: 1.0.0
servers:
  - url: 'https://api.github.com/'
paths:
  /repos/{owner}/{repo}/contributors:
    get:
      tags:
        - github
      summary: Get contributors
      operationId: getContributors
      description: Returns all contributors of a certain GitHub repository
      parameters:
        - name: owner
          in: path
          description: owner to fetch
          required: true
          schema:
            type: string
        - name: repo
          in: path
          description: repo to fetch
          required: true
          schema:
            type: string
        - name: per_page
          in: query
          schema:
            type: integer
            format: int32
        - name: page
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A list of contributors.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contributor'
components:
  schemas:
    Contributor:
      type: object
      properties:
        login:
          type: string
        contributions:
          type: number
          format: integer
