quarkus:
  flyway:
    migrate-at-start: true
  datasource:
    db-kind: postgresql
    username: quarkus
    password: quarkus
    jdbc:
      url: jdbc:postgresql://localhost:6543/quarkus
    devservices:
      enabled: true
      port: 6543
  scheduler:
    metrics:
      enabled: true

shedlock:
  defaults:
    lock-at-most-for: PT20S
