/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.simonscholz

import dev.simonscholz.api.client.fft.api.InboundInventoryApi
import dev.simonscholz.api.client.fft.invoker.ApiClient
import dev.simonscholz.api.client.fft.model.InboundProcessPurchaseOrderForUpsertDTO
import io.github.cdimascio.dotenv.dotenv

fun main() {
    val dotenv = dotenv()

    val baseUri = dotenv["baseUri"]
    val bearerToken = dotenv["bearerToken"]
    val inboundProcessId = "019d4885-734b-7706-bf59-cf49e231d8c9"
    val newQty = 10

    val authorizationHeader =
        mapOf(
            "Authorization" to "Bearer $bearerToken",
        )

    val apiClient = ApiClient()
    apiClient.updateBaseUri(baseUri)
    val api = InboundInventoryApi(apiClient)
    val inboundProcess = api.getInboundProcess(inboundProcessId, authorizationHeader)

    val purchaseOrder =
        requireNotNull(inboundProcess.purchaseOrder) {
            "Purchase order must not be null for inbound process with id $inboundProcessId"
        }

    val requestedItems =
        purchaseOrder.requestedItems.map {
            println("Current quantity for item ${it.tenantArticleId} is ${it.quantity.value} and will be updated to $newQty")
            val modifiedQty =
                it.quantity.apply {
                    value = newQty
                }
            it.quantity(modifiedQty)
        }

    val updateDTO =
        InboundProcessPurchaseOrderForUpsertDTO()
            .version(inboundProcess.version)
            .requestedItems(
                requestedItems,
            ).orderDate(purchaseOrder.orderDate)
            .requestedDate(purchaseOrder.requestedDate)

    val response =
        api.upsertInboundProcessPurchaseOrder(
            inboundProcessId,
            updateDTO,
            authorizationHeader,
        )

    println("Response from FFT:")
    println(response)
}
