/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.openapi)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.dotenv)
    implementation(libs.jackson)
    implementation(libs.jackson.jsr310)
    implementation(libs.jakarta.annotation)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "dev.simonscholz.AppKt"
}

configureOpenApiClient(
    taskName = "generateFftApiClient",
    spec = "$rootDir/stripped-fft-api.yaml",
    basePackage = "dev.simonscholz.api.client.fft",
)

fun configureOpenApiClient(
    taskName: String,
    spec: String,
    basePackage: String,
) {
    tasks.register(taskName, GenerateTask::class.java) {
        generatorName.set("java")

        inputSpec.set(spec)
        outputDir.set("${layout.buildDirectory.get()}/generated")

        packageName.set(basePackage)
        apiPackage.set("$basePackage.api")
        modelPackage.set("$basePackage.model")
        modelNameSuffix.set("DTO")
        invokerPackage.set("$basePackage.invoker")

        // Use Java 11 HttpClient
        library.set("native")

        generateModelTests.set(false)
        generateApiTests.set(false)

        configOptions.set(
            mapOf(
                "library" to "native",
                "enumPropertyNaming" to "MACRO_CASE",
                "dateLibrary" to "java8",
                "openApiNullable" to "false",
                "useJakartaEe" to "true",
                "serializationLibrary" to "jackson",
                "hideGenerationTimestamp" to "true",
            ),
        )

        globalProperties.set(
            mapOf(
                "models" to "", // generate DTOs
                "apis" to "", // generate API interfaces
                "supportingFiles" to "",
            ),
        )

        generateModelTests.set(false)
        generateApiTests.set(false)
        generateModelDocumentation.set(false)
        generateApiDocumentation.set(false)
    }
}

sourceSets {
    main {
        java {
            srcDir("${layout.buildDirectory.get()}/generated/src/main/java")
        }
    }
}
