query InboundProcesses($status:InboundProcessStatus!, $after: String) {
    inboundProcessesV2(filter: {status: {eq: $status}}, first: 100, after: $after) {
        pageInfo {
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
        }
        edges {
            node {
                id
                version
                facilityRef
                purchaseOrder {
                    requestedItems {
                        quantity {
                            value
                        }
                    }
                    requestedDate {
                        value
                    }
                }
            }
        }
    }
}